version: "3.3"
services:
  springboot-app:
    container_name: spring_app_backend
    image: lakshmihegdeiiitb/spring
    restart: always
    ports:
      - 9088:9087
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysqldatabase
      MYSQL_PORT: 3306

  mysql_service:
    container_name: mysqldatabase
    image: mysql
    ports:
      - 3308:3306
    volumes:
      - /home/lakshmi/Documents/Database :/var/lib/mysql
    environment:
      MYSQL_DATABASE: GiftDB
      MYSQL_ROOT_PASSWORD : root
  
  react_app:
    container_name: react_app_frontend
    image: lakshmihegdeiiitb/react
    restart: always
    ports: 
      - 3001:3000
      
